// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-H4MbYRA_cBljhpm7-JfjPeFaYJ-Ek00',
    appId: '1:399854354890:web:9c0065a986d299b9ec0f33',
    messagingSenderId: '399854354890',
    projectId: 'plantpal-87d69',
    authDomain: 'plantpal-87d69.firebaseapp.com',
    storageBucket: 'plantpal-87d69.appspot.com',
    measurementId: 'G-H81TNNDVYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJ0Ehls_V7_TuG7a8AoZpZaUPpPd6KA8',
    appId: '1:399854354890:android:907c6c7d57c8297aec0f33',
    messagingSenderId: '399854354890',
    projectId: 'plantpal-87d69',
    storageBucket: 'plantpal-87d69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQzIyAzujRPBuqseepf47-VkgDqqCyi3U',
    appId: '1:399854354890:ios:35aa009564238db1ec0f33',
    messagingSenderId: '399854354890',
    projectId: 'plantpal-87d69',
    storageBucket: 'plantpal-87d69.appspot.com',
    iosBundleId: 'com.example.plantCareApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQzIyAzujRPBuqseepf47-VkgDqqCyi3U',
    appId: '1:399854354890:ios:35aa009564238db1ec0f33',
    messagingSenderId: '399854354890',
    projectId: 'plantpal-87d69',
    storageBucket: 'plantpal-87d69.appspot.com',
    iosBundleId: 'com.example.plantCareApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-H4MbYRA_cBljhpm7-JfjPeFaYJ-Ek00',
    appId: '1:399854354890:web:6999ab1c48973145ec0f33',
    messagingSenderId: '399854354890',
    projectId: 'plantpal-87d69',
    authDomain: 'plantpal-87d69.firebaseapp.com',
    storageBucket: 'plantpal-87d69.appspot.com',
    measurementId: 'G-0RMEG6K8QT',
  );
}
